{% set name = "xcape" %}
{% set version = "0.1.1" %}
{% set sha256 = "344812b7a52cf9ec32fd1d2df00f77fa9e65a4c7a508d622da9c460d21f46389" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xgcm/xcape/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - pip
    - numpy 1.16
  run:
    - python
    - xarray >=0.14.1
    - dask
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - xcape.core

about:
  home: https://github.com/xgcm/xcape
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast convective parameters for numpy, dask, and xarray

extra:
  recipe-maintainers:
    - chiaral
    - rabernat
    - xebadir
