{% set name = "xcape" %}
{% set version = "0.1.4" %}
{% set sha256 = "3dfac0cc3c391f7375af51979d66cafa99119da019f8e53ca8c02ba3d83dc887" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xgcm/xcape/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib("c") }}    # [win]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - xarray >=0.14.1
    - dask

test:
  imports:
    - xcape.core

about:
  home: https://github.com/xgcm/xcape
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast convective parameters for numpy, dask, and xarray

extra:
  recipe-maintainers:
    - chiaral
    - rabernat
    - xebadir
